# Generated by Django 3.2.8 on 2021-10-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(unique=True, verbose_name='手机号'),
        ),
    ]
