# Generated by Django 3.2.8 on 2021-12-09 10:38

import backend.utils.basemodel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', backend.utils.basemodel.CustomDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.basemodel.CustomDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='', verbose_name='图片地址')),
                ('theme', models.SmallIntegerField(choices=[(0, '科技前沿'), (1, '娱乐八卦'), (2, '党政新风'), (3, '街电吐槽'), (4, '低息贷款'), (5, '半夜相亲')], unique=True, verbose_name='主题')),
                ('tag', models.CharField(default='room', max_length=20)),
            ],
            options={
                'verbose_name': '聊天室主题图片',
                'verbose_name_plural': '聊天室主题图片',
                'db_table': 'room_theme',
            },
        ),
    ]
