# Generated by Django 3.2.8 on 2021-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻标题')),
                ('summary', models.TextField(blank=True, max_length=400, null=True, verbose_name='新闻简介')),
                ('detail_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='新闻详情链接')),
                ('img_url', models.CharField(blank=True, max_length=350, null=True, verbose_name='新闻插图链接链接')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='新闻分类标签')),
            ],
            options={
                'verbose_name': '汽车之家-新闻数据',
                'verbose_name_plural': '汽车之家-新闻数据',
                'db_table': 'news',
            },
        ),
    ]
